version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    command: sh -c "python bot.py"
    volumes:
      - .:/app
    depends_on:
      - postgres