version: '3'
services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  telegram_bot:
    build: .
    command: sh -c "python bot.py"
    depends_on:
      - postgres_db


